//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorWebForum.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebForumEntities : DbContext
    {
        public WebForumEntities()
            : base("name=WebForumEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<experience> experiences { get; set; }
        public virtual DbSet<location> locations { get; set; }
        public virtual DbSet<post> posts { get; set; }
        public virtual DbSet<profile> profiles { get; set; }
        public virtual DbSet<reply> replies { get; set; }
        public virtual DbSet<specialization> specializations { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
