//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorWebForum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class profile
    {
        public int id { get; set; }
        public int users_id { get; set; }
        public int location_id { get; set; }
        public int professional_id { get; set; }
        public int experience_id { get; set; }
        public string name { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public bool gender { get; set; }
        public Nullable<int> phone { get; set; }
        public string qualification { get; set; }
        public string aichievement { get; set; }
        public string img { get; set; }
    
        public virtual experience experience { get; set; }
        public virtual location location { get; set; }
        public virtual specialization specialization { get; set; }
        public virtual user user { get; set; }
    }
}
