//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorWebForum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reply
    {
        public int id { get; set; }
        public int post_id { get; set; }
        public int users_id { get; set; }
        public string content { get; set; }
        public System.DateTime created_at { get; set; }
        public virtual post post { get; set; }
        public virtual user user { get; set; }
    }
}
